# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiMutu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.BooleanField()),
                ('tahun', models.PositiveIntegerField()),
                ('nilai', models.CharField(choices=[('A', 'A'), ('AB', 'AB'), ('B', 'B'), ('BC', 'BC'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=2)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mahasiswa',
            name='angkatan',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nilaimutu',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Mahasiswa'),
        ),
    ]
